inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'app/validators/DNI_validator.rb'
    - 'spec/validators/DNI_validator_spec.rb'
