version: "3.8"
services:
  database:
    image: postgres:13.2
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: adm_asaaf
    env_file:
      - db-passwd.env

  web:
    image: adm_asaaf:bin-rails
    volumes:
      - ./log:/admasaaf/log:cached
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always
    environment:
      BUNDLE_APP_CONFIG: .bundle
      RAILS_ENV: production
      POSTGRES_NAME: adm_asaaf
      POSTGRES_USER: adm_asaaf
      POSTGRES_URL: postgres://database:5432
      RAILS_SERVE_STATIC_FILES: "true"
    env_file:
      - db-passwd.env

volumes:
  db_data:
  log:
