default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: adm_asaaf_dev
  username: postgres
  password: <%= Rails.application.credentials.dig Rails.env.to_sym, :postgres, :password %>

test:
  <<: *default
  database: adm_asaaf_test
  username: postgres
  password: 1234

production:
  <<: *default
  database: adm_asaaf
  username: adm_asaaf
  password: <%= Rails.application.credentials.dig Rails.env.to_sym, :postgres, :password %>
