name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_DB: adm_asaaf_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up ruby version used
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: |
          sudo apt-get install -yqq libpq-dev
          gem install bundler
          npm install -g yarn
          bundle install --jobs 4 --retry 3

      - name: Setup the app
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
          yarn:install
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: Run RSpec tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
