name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.2
        env:
          POSTGRES_DB: adm_asaaf_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up ruby version used
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup the app
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      - name: Run RSpec tests
        run: bundle exec rspec
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
