name: Push to ECR
on:
  push:
    tags:
      - '*'

jobs:
  ECR:
    name: Push the image of the website to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kciter/aws-ecr-action@master
        env: 
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: admasaaf
          region: eu-west-3
          tags: latest,${{ github.event.release.tag_name }}
          extra_build_args: -t ${{ secrets.AWS_ACCOUNT_ID }}dkr.ecr.eu-west-3.amazonaws.com/admasaaf:latest
